name: Integrity

on:
  push:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/integrity.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ“¥ Install dependencies
        uses: ./.github/actions/setup

      - name: ğŸ‘¬ğŸ½ Check for duplicate dependencies in lock file
        run: |
          pnpm manypkg check
          pnpm dedupe --check
