name: Monorepo Integrity

on:
  push:
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ“¥ install
        uses: ./.github/actions/setup

      - name: ğŸ‘¬ğŸ½ Check for duplicate dependencies in lock file
        run: |
          pnpm manypkg check
          pnpm dedupe --check